export * from './api/dashboard'
export * from './api/user'
export * from './api/role'
export * from './api/dance'
export * from './api/dance_type'
export * from './api/dance_move'
export * from './api/dance_part'
export * from './api/dance_cloth'
export * from './api/quiz'
export * from './api/quiz_option'
export * from './api/quiz_question'
export * from './api/quiz_attempt'
export * from './api/quiz_result'
export * from './api/student_answer'
export * from './api/login'
export * from './api/system'
export * from './api/test'

export const API_URL = `${import.meta.env.VITE_API_URL}/api/v1`
